### ISSUE TITLE
[Feat] 영화 세부 정보 조회 API 구현

### ISSUE THREAD

**Issue by jjuny-won** [SOPT-all/35-COLLABORATION-SERVER-CGV#3]
## 📌  Feature Issue
영화 세부 정보 조회 API 구현

![Screenshot 2024-11-18 at 12 05 50 PM](https://github.com/user-attachments/assets/2f8444e6-2b05-453a-9c68-10e1c464caec)

## 📝  To-do

- [x] .gitignore 추가
- [x] mysql dependency 추가
- [x] 테이블 (Entity ) 생성
- [x] 세부 정보 조회 로직 구현
